### PR TITLE
Update appveyor.yml

### PR DESCRIPTION
**Pull request by pat-s**
I've found the following setup working fine in my projects recently.

Caching `pandoc` clears some confusion for the user, even though `pandoc` is strictly not required. 

The problem with caching pandoc is that `pandoc` won't be upgraded unless its cache is invalidated from time to time.

PS: The appveyor builds have to be enabled again after moving to `ropenscilabs`.

### CODE REVIEW

**Comment by pat-s** [comment]
Thinking about it again, I think we should omit `pandoc` because I saw several segfaults when using `pandoc` on appveyor. Also, `pandoc` won't be updated if the cached version is used.

Additionally, I would suggest calling `rcmdcheck` with the following options:

```r
add_step(step_rcmdcheck(args = c("--as-cran", "--no-manual", "--no-vignettes",
        "--no-build-vignettes", "--no-multiarch"), build_args = c("--no-build-vignettes"), error_on = "error"))
```

This clears all LaTeX and pandoc related problems and ensures a smooth check of the remaining part including tests.

**Comment by pat-s** [comment]
Hm, this would make `tic.R` quite messy and also `add_package_checks()` kind of obsolete for now. Not sure if we want this. But I do not see an easy way to use a default `step_rcmcheck()` on Appveyor?

**Comment by pat-s** [comment]
And I experienced that when using `C:\RLibrary` caching is not used. One needs to use `C:\RLibrary\` to get it working.

**Comment by krlmlr** [comment]
Thanks for investigating. Are you suggesting to make the additional build switches the default for Windows? We could use `build_args = NULL` as default in `step_rcmdcheck()` and decide based on the operating system.

**Comment by pat-s** [comment]
> Thanks for investigating. Are you suggesting to make the additional build switches the default for Windows? We could use build_args = NULL as default in step_rcmdcheck() and decide based on the operating system.

Yes, this would make life a lot easier. It is a pain to get LaTeX and pandoc working on Appveyor and they continuously cause trouble. 

Your suggestion sounds good. I'll make a PR in tic and document the defaults.

**Comment by pat-s** [comment]
superseeded by #5

**Pull request closed without merging**
